site_name: Documentación del Proyecto
site_description: Proyecto de documentación técnica
site_author: Danny



theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search:
      lang: es 
 
nav:
  - Inicio: index.md
  - Salesforce:
      - Introducción: salesforce/index.md
      - API de Salesforce: salesforce/api.md
  - Java:
      - Introducción: java/index.md
      - Hibernate: java/hibernate.md
  - .NET:
      - Introducción: dotnet/index.md
  - Imágenes: images/index.md
  - Ejemplos de Apex: docs/ApexExamples.md
  - Power Apps: power-apps.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
